"""add_banner_image_to_profiles

Revision ID: 75814a28abc6
Revises: c90b45ef88a2
Create Date: 2026-07-03 13:01:49.640808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75814a28abc6'
down_revision: Union[str, Sequence[str], None] = 'c90b45ef88a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('banner_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'banner_image')
    # ### end Alembic commands ###
